name: Build vllm-rocm
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Docker Image
        run: |
          docker pull vllm/vllm-openai:latest-rocm
          docker save vllm/vllm-openai:latest-rocm | gzip > vllm-rocm.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vllm-rocm-image
          path: vllm-rocm.tar.gz
