name: Build vllm-rocm
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Docker Image
        run: |
          docker pull vllm/vllm-openai-rocm:nightly
          docker save vllm/vllm-openai-rocm:nightly | gzip > vllm-rocm.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vllm-rocm-image
          path: vllm-rocm.tar.gz
          retention-days: 7
