name: Sync comfyui:0.24.0-amd-rdna3
on:
  workflow_dispatch

env:
  ACR_REG: crpi-legts7bsv7grb58e.cn-hangzhou.personal.cr.aliyuncs.com
  SRC: docker.io/sinfallas/comfyui:0.24.0-amd-rdna3
  DST: docker://crpi-legts7bsv7grb58e.cn-hangzhou.personal.cr.aliyuncs.com/jeff-proxy/sinfallas/comfyui:0.24.0-amd-rdna3

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install skopeo
        run: sudo apt update && sudo apt install -y skopeo

      - name: Sync image to Aliyun ACR
        run: |
          skopeo copy \
            --src-tls-verify=false \
            --dest-tls-verify=false \
            --dest-creds ${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }} \
            docker://${{ env.SRC }} \
            docker://${{ env.DST }}
