name: Sync Large Docker Image

on:
  workflow_dispatch:

jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Sync Image to Aliyun
        env:
          ALI_USER: ${{ secrets.ALIYUN_USERNAME }}
          ALI_PASS: ${{ secrets.ALIYUN_PASSWORD }}
        run: |
          skopeo copy \
            --src-creds "" \
            --dest-creds "$ALI_USER:$ALI_PASS" \
            docker://corundex/comfyui-rocm:latest \
            docker://crpi-legts7bsv7grb58e.cn-hangzhou.personal.cr.aliyuncs.com/jeff-proxy/comfyui-rocm:latest
